name: crud_local
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.1.3

dependencies:

  function_tree: ^0.9.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared_preferences: ^2.2.0
  provider: ^6.1.1
  awesome_dialog: ^3.1.0
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter_icons:

  android: true
  ios: true
  image_path: "assets/images/logoapp.png"
  adaptive_icon_background: "#347aeb"
  adaptive_icon_foreground: "assets/images/logoapp.png"

flutter:

 uses-material-design: true
 assets:
    - assets/images/logoapp.png
    - assets/images/nf.png

  